apiVersion: v1
kind: ConfigMap
metadata:
  name: backstageio-conn-cm
  namespace: backstage
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: backstageio-host
  namespace: backstage
spec:
  to:
    name: backstageio-conn-cm
    kind: configmap
  from:
    path: ".status.endpoint.address"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: backstageio
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: backstageio-port
  namespace: backstage
spec:
  to:
    name: backstageio-conn-cm
    kind: configmap
  from:
    path: ".status.endpoint.port"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: backstageio
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: backstageio-user
  namespace: backstage
spec:
  to:
    name: backstageio-conn-cm
    kind: configmap
  from:
    path: ".spec.masterUsername"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: backstageio